### ISSUE TITLE
Setup testing framework for Cloudmos API

### ISSUE THREAD

**Issue by baktun14** [akash-network/console#122]
We don't currently do any unit tests in the API. Now that we're slowly scaling the team, it is a great idea to start covering some of the code, especially the versionned API.

**TODO**
- [x] Define the structure for tests
- [x] Add jest to API
- [x] Add a few tests (functional/integration/unit)

**Comment by ygrishajev** [comment]
Implemented by https://github.com/akash-network/cloudmos/pull/126
