### ISSUE TITLE
Implement graceful shutdown

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#141]
This is essential for several purposes:
1) functional testing when server and all the deps termination (dbs, caching etc)
2) proper scaling scenarios

Basically before application is actually closed several things need to happen on SIGTERM:
1) server should stop accepting new connections while finishing the ones in progress
2) ones that's done db connections needs to be closed
3) this should be triggered by a method that can be used in tests or in a termination event handler

**Tasks:**
- [ ] implement graceful shutdown
- [ ] attach it to a process termination event
- [ ] use it for functional tests teardown
