### ISSUE TITLE
Deploy cloudmos services to k8s

### ISSUE THREAD

**Issue by ygrishajev** [akash-network/console#146]
Currently the deploy process is manual. Which rises quite some issues with some root ones:
1) infra not transparent enough
2) scaling strategies is not flexible enough
3) resources allocation is not flexible enough
4) harder to onboard new devs
5) harder to move infra
etc.

Something that could address this issues and provide for much more opportunities is k8s which we can easily utilise within GKE.

**Tasks:**

- [ ] Spin up 2 new GKE clusters for dev and prod (needs confirmation, may be some existing one would be used)
- [ ] Deploy all the services to both clusters: api, indexer, web, landing
- [ ] Update CD to deploy. This should first go with a dedicated proposal. A dedicated ticket might make sense

**Comment by anilmurty** [comment]
Ideally we would want to deploy this to Akash providers - we have done this for Console previously
